# Generated by Django 4.2.7 on 2023-12-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_link', models.CharField(max_length=100)),
                ('link_name', models.CharField(max_length=30)),
            ],
        ),
    ]
